version: '3'
services:
  database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=hedgedoc
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:${HEDGEDOC_VERSION}
    environment:
      - CMD_DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_USER}@database:5432/hedgedoc
      - CMD_DOMAIN=${CMD_DOMAIN}
      - CMD_URL_ADDPORT=${CMD_URL_ADDPORT}
      - CMD_ALLOW_ANONYMOUS=${CMD_ALLOW_ANONYMOUS}
      - CMD_ALLOW_ANONYMOUS_EDITS=${CMD_ALLOW_ANONYMOUS_EDITS}
      - CMD_EMAIL=${CMD_EMAIL}
      - CMD_GITHUB_CLIENTID=${CMD_GITHUB_CLIENTID}
      - CMD_GITHUB_CLIENTSECRET=${CMD_GITHUB_CLIENTSECRET}
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
volumes:
  database:
  uploads: